### ISSUE TITLE
include git information

### ISSUE THREAD

**Issue by sbowman-mitre** [buffetboy2001/cppmanifest#2]
When this is used in a git project, it should also report the information from `git describe`. This will improve trace-ability between builds.

**Comment by sbowman-mitre** [comment]
This may not be the best command, actually. It describes the parent tag, but not the current SHA. More investigation may be necessary.

**Comment by sbowman-mitre** [comment]
Here's a helpful conversation with different ideas. http://stackoverflow.com/questions/1435953/how-can-i-pass-git-sha1-to-compiler-as-definition-using-cmake

**Comment by sbowman-mitre** [comment]
See also a preformed solution: https://github.com/rpavlik/cmake-modules/blob/master/GetGitRevisionDescription.cmake

**Comment by buffetboy2001** [comment]
completed with rev b54417142
